#!/usr/bin/env python

import urllib2
import json
import sys
import random

# TODO find issues not in your repos
# TODO weight based on various things
 # how many comments
 # age
 # ..etc?
# TODO work with private repos, etc.

def usage() :
	print 'usage: githubroulette <username> [n=number of issues to show]'
	sys.exit(1)

if __name__ == '__main__' :
	try :
		username = sys.argv[1]
	except IndexError :
		usage()
	
	try :
		n = int(sys.argv[2])
		if (n < 1) :
			print 'n must be >= 1\n'
			usage()
	except IndexError :
		n = 1
	
	repos_fa = json.load(urllib2.urlopen('https://api.github.com/users/%s/repos' % username))
	repos = [r['name'] for r in repos_fa if r['open_issues'] > 0]
	del repos_fa

	open_issues = list()

	for repo in repos :
		issues_fa = json.load(urllib2.urlopen('https://api.github.com/repos/%s/%s/issues' % (username, repo)))
		open_issues += [('https://github.com/%s/%s/issues/%d' % (username, repo, issue['number']), issue['title']) for issue in issues_fa if issue['state'] == 'open']

	if not open_issues :
		print 'congratulations, you are free of issues. go outside.'
		sys.exit(0)
	
	random.shuffle(open_issues)

	url_max = 0
	for i in range(n) :
		url_max = max(url_max, len(open_issues[i][0]))

	for i in range(n) :
		url, title = open_issues[i]
		print '%s  %s' % (url.ljust(url_max), title)
